upgrade modules to  user provider v6
GoogleCloudPlatform/terraform-google-cloud-run pull request #257
Opened 2024-11-02 02:46 UTC by daniel-cit

This PR upgrade the modules to  user Terraform Google provider v6.x

2024-11-04 20:24 UTC, daniel-cit commented
/gcbrun

2024-11-04 20:53 UTC, apeabody commented
/gcbrun

2024-11-04 20:53 UTC, apeabody requested changes
Thanks @daniel-cit!

2024-11-04 20:53 UTC, apeabody commented on docs/upgrading_to_cloud_run_v2_v0.14.0_from_v0.13.0.md
> +The cloud-run/v2 release v0.13.0 is backward incompatible.
```suggestion
The cloud-run/v2 release v0.14.0 is backward incompatible.
```

2024-11-05 19:46 UTC, daniel-cit commented
@apeabody Could you please try to run the integration tests again?

2024-11-05 19:47 UTC, apeabody commented
/gcbrun

2024-11-05 21:22 UTC, apeabody commented
/gcbrun

2024-11-05 22:05 UTC, apeabody approved these changes

2024-11-05 22:06 UTC, merged